### ISSUE TITLE
exec sbt dalvik fail, see more detail below 

### ISSUE THREAD

**Issue by iamfaith** [wuhx/setpropex#1]
[info] Loading project definition from /Users/faith/Desktop/setpropex/project
[info] Set current project to setpropex (in build file:/Users/faith/Desktop/setpropex/)
[info] Including from cache: setpropex_2.11-0.1-SNAPSHOT.jar
[info] Including from cache: jna-4.2.1.jar
[info] Including from cache: scala-library-2.11.8.jar
[info] Checking every *.class/*.jar file's SHA-1.
[info] Merging files...
[warn] Merging 'META-INF/MANIFEST.MF' with strategy 'discard'
[warn] Strategy 'discard' was applied to a file
[info] Assembly up to date: /Users/faith/Desktop/setpropex/target/scala-2.11/setpropex-assembly-0.1-SNAPSHOT.jar
java.io.IOException: Cannot run program "dx": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
	at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:126)
	at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:154)
	at $6c0704486289533ae424$$anonfun$$sbtdef$1.apply(/Users/faith/Desktop/setpropex/build.sbt:23)
	at $6c0704486289533ae424$$anonfun$$sbtdef$1.apply(/Users/faith/Desktop/setpropex/build.sbt:18)
	at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:54)
	at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:53)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
	at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:126)
	at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:154)
	at $6c0704486289533ae424$$anonfun$$sbtdef$1.apply(/Users/faith/Desktop/setpropex/build.sbt:23)
	at $6c0704486289533ae424$$anonfun$$sbtdef$1.apply(/Users/faith/Desktop/setpropex/build.sbt:18)
	at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:54)
	at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:53)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:dalvik) java.io.IOException: Cannot run program "dx": error=2, No such file or directory
[error] Total time: 1 s, completed 2017-4-5 9:18:56

**Comment by wuhx** [comment]
dx should in your system PATH
or you can add location prefix to dx in build.sbt
eg: if you install android SDK by SBT, it's something like ~/.android/sbt/sdk/build-tools/24.0.1/dx
